/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const cropPositionClass: typeof import('./src/composables/cropPosition').cropPositionClass
  const firstCropPositionClass: typeof import('./src/composables/cropPosition').firstCropPositionClass
  const reader: typeof import('./src/composables/reader').reader
  const stripMarkdown: typeof import('./src/composables/markdown').stripMarkdown
}
